# Generated by Django 4.2.7 on 2026-06-16 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userskill",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_skills",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["name"], name="skills_skil_name_c82d47_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["level"], name="skills_skil_level_f66b7e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userskill",
            unique_together={("user", "skill")},
        ),
    ]
